import unittest
from pathlib import Path


class ReadmeTests(unittest.TestCase):
    def test_readme_shows_demo_and_output_preview(self):
        readme = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("python -m agent_workbench demo", readme)
        self.assertIn("[中文完整版](README.zh-CN.md)", readme)
        self.assertIn("## 中文介绍", readme)
        self.assertIn("## English Introduction", readme)
        self.assertLess(readme.index("## 中文介绍"), readme.index("## English Introduction"))
        self.assertIn("agent-workbench demo --adapter all --check --print-kickoff", readme)
        self.assertIn("agent-workbench demo --adapter all --check --format json --output-json .agent-workbench/demo-proof.json", readme)
        self.assertIn("agent-workbench init . --output .agent-workbench --adapter all --check --format json --output-json .agent-workbench/init-proof.json", readme)
        self.assertIn("Text output prints a `Proof:` line", readme)
        self.assertIn("including adapter and existing agent asset counts", readme)
        self.assertIn("compact artifact summary", readme)
        self.assertIn("copyable `proof_summary`", readme)
        self.assertIn("first verification command", readme)
        self.assertIn("Existing agent assets", readme)
        self.assertIn("Scan JSON also includes `agent_assets`", readme)
        self.assertIn("The demo repository includes a safe `.github/copilot-instructions.md`", readme)
        self.assertIn("existing `agent_assets`", readme)
        self.assertIn(".github/copilot-instructions.md", readme)
        self.assertIn("GEMINI.md", readme)
        self.assertIn("--print-kickoff", readme)
        self.assertIn("--format text|json", readme)
        self.assertIn("python -m agent_workbench init . --output .agent-workbench --project-name my-repo --check", readme)
        self.assertIn("agent-workbench check . --format json", readme)
        self.assertIn("agent-workbench check . --strict --format json", readme)
        self.assertIn("agent-workbench check . --adapter all --format json", readme)
        self.assertIn("agent-workbench check . --format json --output-json .agent-workbench/readiness.json", readme)
        self.assertIn("validates optional Claude Code, Codex, Cursor, and OpenCode handoff files", readme)
        self.assertIn("Use `--adapter all` to require all four handoffs", readme)
        self.assertIn("Use `--strict` in CI", readme)
        self.assertIn("JSON readiness reports include `next_action`", readme)
        self.assertIn("python -m agent_workbench scan . --format json --output-json .agent-workbench/repo-map.json", readme)
        self.assertIn("python -m agent_workbench scan . --format json", readme)
        self.assertIn("agent-workbench check [ROOT]", readme)
        self.assertIn("agent-workbench scan [ROOT] [--format text|json]", readme)
        self.assertIn("$ agent-workbench demo", readme)
        self.assertIn("$ tree .agent-workbench", readme)
        self.assertIn("--adapter claude|codex|cursor|opencode|all", readme)
        self.assertIn(".agent-workbench/", readme)
        self.assertIn("AGENTS.md", readme)
        self.assertIn("agent-task-pack.md", readme)
        self.assertIn("## Kickoff Prompt", readme)
        self.assertIn("## Verification Commands", readme)
        self.assertIn("examples/python-cli/source", readme)
        self.assertIn("examples/python-cli/agent-workbench/AGENTS.md", readme)
        self.assertIn("examples/typescript-cli/source", readme)
        self.assertIn("examples/typescript-cli/agent-workbench/AGENTS.md", readme)
        self.assertIn("uv tool install git+https://github.com/Xiao-rx/agent-workbench.git", readme)
        self.assertIn("docs/release-v0.8.0.md", readme)
        self.assertIn("Latest published release", readme)
        self.assertIn("releases/tag/v0.7.0", readme)
        self.assertIn("docs/launch-kit.md", readme)
        self.assertIn("python -m github_trend_lab insight --decisions reports/daily-decisions.json", readme)
        self.assertIn("`trend-lab insight` is a local shortcut", readme)
        self.assertIn("provider-neutral", readme.lower())
        self.assertIn("用一条命令把任意代码仓库变成 AI coding agent 可以安全接手的工作区", readme)
        self.assertIn("默认输出不绑定任何模型或工具", readme)

    def test_chinese_readme_covers_first_run_path(self):
        readme = Path("README.zh-CN.md").read_text(encoding="utf-8")

        self.assertIn("[English](README.md)", readme)
        self.assertIn("用一条命令把任意代码仓库变成 AI coding agent 可以安全接手的工作区", readme)
        self.assertIn("agent-workbench demo --adapter all --check --print-kickoff", readme)
        self.assertIn("agent-workbench demo --adapter all --check --format json --output-json .agent-workbench/demo-proof.json", readme)
        self.assertIn("agent-workbench init . --output .agent-workbench --adapter all --check --format json --output-json .agent-workbench/init-proof.json", readme)
        self.assertIn("普通文本输出也会打印 `Proof:` 行", readme)
        self.assertIn("包含 adapter 与现有 agent asset 数量", readme)
        self.assertIn("简要 artifact summary", readme)
        self.assertIn("可复制的 `proof_summary`", readme)
        self.assertIn("首个 verification command", readme)
        self.assertIn("现有 agent 资产探测", readme)
        self.assertIn("scan JSON 也会包含 `agent_assets`", readme)
        self.assertIn("demo 仓库内置一个安全的 `.github/copilot-instructions.md`", readme)
        self.assertIn("现有 `agent_assets`", readme)
        self.assertIn(".github/copilot-instructions.md", readme)
        self.assertIn("GEMINI.md", readme)
        self.assertIn("`--print-kickoff` 会把生成的 kickoff prompt 直接打印到终端", readme)
        self.assertIn("`--adapter all` 会一次生成 Claude Code、Codex、Cursor 和 OpenCode 的轻量适配文件", readme)
        self.assertIn(".codex/AGENTS.md", readme)
        self.assertIn("opencode.json", readme)
        self.assertIn("agent-workbench init . --output .agent-workbench --project-name my-repo --check", readme)
        self.assertIn("agent-workbench check . --format json", readme)
        self.assertIn("agent-workbench check . --strict --format json", readme)
        self.assertIn("agent-workbench check . --adapter all --format json", readme)
        self.assertIn("agent-workbench check . --format json --output-json .agent-workbench/readiness.json", readme)
        self.assertIn("如果存在 Claude Code、Codex、Cursor 或 OpenCode handoff 文件", readme)
        self.assertIn("在 CI 里可以加 `--strict`", readme)
        self.assertIn("JSON readiness 报告会包含 `next_action`", readme)
        self.assertIn("agent-workbench scan . --format json", readme)
        self.assertIn("examples/typescript-cli/source", readme)
        self.assertIn("python -m github_trend_lab insight --decisions reports/daily-decisions.json", readme)
        self.assertIn("快速查看最新决策摘要", readme)
        self.assertIn("趋势分析不是产品本体", readme)


if __name__ == "__main__":
    unittest.main()
