import unittest
from pathlib import Path


class LaunchKitTests(unittest.TestCase):
    def test_launch_kit_contains_shareable_assets(self):
        launch = Path("docs/launch-kit.md").read_text(encoding="utf-8")
        preview = Path("assets/social-preview.svg").read_text(encoding="utf-8")

        self.assertIn("Turn any repository into an AI-agent-ready workspace", launch)
        self.assertIn("Show HN", launch)
        self.assertIn("Share Post Draft", launch)
        self.assertIn("After publishing v0.8.0", launch)
        self.assertIn("--adapter all", launch)
        self.assertIn("agent-workbench demo --adapter all --strict --print-kickoff", launch)
        self.assertIn("agent-workbench demo --proof", launch)
        self.assertIn("agent-workbench demo --report", launch)
        self.assertIn("agent-workbench init . --output .agent-workbench --proof", launch)
        self.assertIn("copyable `Proof:` line", launch)
        self.assertIn("adapter and existing agent asset counts", launch)
        self.assertIn("exact readiness gate command", launch)
        self.assertIn("automatically runs the readiness check", launch)
        self.assertIn("demo --proof [PATH]", launch)
        self.assertIn("demo --report [PATH]", launch)
        self.assertIn("init --proof [PATH]", launch)
        self.assertIn("defaults the proof path inside the generated workbench", launch)
        self.assertIn("prints copyable `Proof:` and `Proof command:` lines", launch)
        self.assertIn("--print-kickoff", launch)
        self.assertIn("demo --format json", launch)
        self.assertIn("init --format json", launch)
        self.assertIn("artifact summary", launch)
        self.assertIn("copyable proof summary", launch)
        self.assertIn("proof command for the shortcut path", launch)
        self.assertIn("Demo report: a shareable Markdown artifact", launch)
        self.assertIn("verification command", launch)
        self.assertIn("readiness command", launch)
        self.assertIn("structured readiness args", launch)
        self.assertIn("pre-write existing agent assets", launch)
        self.assertIn("readiness counts when checks run", launch)
        self.assertIn("readiness summary", launch)
        self.assertIn("readiness counts", launch)
        self.assertIn("structured handoff paths", launch)
        self.assertIn("schema metadata", launch)
        self.assertIn("no-secret demo includes a safe `.github/copilot-instructions.md`", launch)
        self.assertIn("Agent Workbench does not need credentials", launch)
        self.assertIn("`.env.example` is a placeholder-only template", launch)
        self.assertIn("`.env.local` stays ignored", launch)
        self.assertIn("Copilot, Gemini, and OpenCode instruction files", launch)
        self.assertIn("Codex adapter", launch)
        self.assertIn("OpenCode adapter", launch)
        self.assertIn("opencode.json", launch)
        self.assertIn("agent-workbench check . --format json", launch)
        self.assertIn("agent-workbench scan . --output-json .agent-workbench/repo-map.json", launch)
        self.assertIn("agent-workbench check . --output-json .agent-workbench/readiness.json", launch)
        self.assertIn("the option implies JSON output", launch)
        self.assertIn("strict all-adapter JSON demo proof and Markdown demo report", launch)
        self.assertIn("trend-lab insight --decisions reports/daily-decisions.json", launch)
        self.assertIn("readiness check", launch)
        self.assertIn("scan JSON", launch)
        self.assertIn("Python and TypeScript", launch)
        self.assertIn("Turn any repository into an AI-agent-ready workspace with AGENTS.md, task packs, adapters, and scan JSON.", launch)
        self.assertIn("developer-tools, llm, productivity", launch)
        self.assertIn("License:", launch)
        self.assertIn("MIT license, so reuse rights are explicit before adoption", launch)
        self.assertIn("It is MIT licensed.", launch)
        self.assertIn("uv tool install git+https://github.com/Xiao-rx/agent-workbench.git", launch)
        self.assertIn("https://github.com/Xiao-rx/agent-workbench/releases/tag/v0.8.0", launch)
        self.assertIn("<svg", preview)
        self.assertIn("Agent Workbench", preview)


if __name__ == "__main__":
    unittest.main()
