import unittest
from pathlib import Path


class ReadmeTests(unittest.TestCase):
    def test_readme_shows_demo_and_output_preview(self):
        readme = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("python -m agent_workbench demo", readme)
        self.assertIn("[完整中文 README](README.zh-CN.md)", readme)
        self.assertIn("**中文**：用一条命令把任意代码仓库变成 AI coding agent 可以安全接手的工作区。", readme)
        self.assertIn("**English**: Turn any repository into an AI-agent-ready workspace with one command.", readme)
        self.assertIn("## 中文介绍", readme)
        self.assertIn("## English Introduction", readme)
        self.assertLess(readme.index("## 中文介绍"), readme.index("## English Introduction"))
        self.assertIn("如果你习惯中文阅读，可以直接看 [README.zh-CN.md](README.zh-CN.md)", readme)
        self.assertIn("agent-workbench demo --adapter all --strict --print-kickoff", readme)
        self.assertIn("agent-workbench demo --proof", readme)
        self.assertIn("`demo --proof [PATH]` writes a strict all-adapter JSON proof", readme)
        self.assertIn("prints the same copyable `Proof:` summary and `Proof command:` line to stdout", readme)
        self.assertIn("agent-workbench init . --output .agent-workbench --proof", readme)
        self.assertIn("`init --proof [PATH]` writes a shareable JSON init proof", readme)
        self.assertIn("Text output prints a `Proof:` line", readme)
        self.assertIn("including adapter and existing agent asset counts", readme)
        self.assertIn("readiness counts when checks run", readme)
        self.assertIn("readiness gate command", readme)
        self.assertIn("The JSON proof includes `kind` and `schema_version`", readme)
        self.assertIn("compact artifact summary", readme)
        self.assertIn("a `handoff` object with `AGENTS.md`, `agent-task-pack.md`, and `next_action`", readme)
        self.assertIn("copyable `proof_summary`", readme)
        self.assertIn("reproducible `proof_command`", readme)
        self.assertIn("first verification command", readme)
        self.assertIn("a `readiness_summary` and `readiness_counts` when checks run", readme)
        self.assertIn("`readiness_command` plus structured `readiness_args`", readme)
        self.assertIn("Python verification commands are only reported when the matching path exists", readme)
        self.assertIn("Existing agent assets", readme)
        self.assertIn("Scan JSON also includes `kind`, `schema_version`, and `agent_assets`", readme)
        self.assertIn("The demo repository includes a safe `.github/copilot-instructions.md`", readme)
        self.assertIn("pre-write existing `agent_assets`", readme)
        self.assertIn(".github/copilot-instructions.md", readme)
        self.assertIn("GEMINI.md", readme)
        self.assertIn("Use `--strict` with `demo` or `init`", readme)
        self.assertIn("it automatically runs the readiness check", readme)
        self.assertIn("--print-kickoff", readme)
        self.assertIn("--format text|json", readme)
        self.assertIn("python -m agent_workbench init . --output .agent-workbench --project-name my-repo --check", readme)
        self.assertIn("Relative `--output` paths are resolved inside the target repository root", readme)
        self.assertIn("Generated Codex and Cursor handoffs point back to the same resolved workbench path", readme)
        self.assertIn("agent-workbench check . --format json", readme)
        self.assertIn("agent-workbench check . --strict --format json", readme)
        self.assertIn("agent-workbench check . --adapter all --format json", readme)
        self.assertIn("agent-workbench check . --output-json .agent-workbench/readiness.json", readme)
        self.assertIn("validates optional Claude Code, Codex, Cursor, and OpenCode handoff files", readme)
        self.assertIn("Use `--adapter all` to require all four handoffs", readme)
        self.assertIn("Use `--strict` in CI", readme)
        self.assertIn("JSON readiness reports include `kind`, `schema_version`, `counts`, and `next_action`", readme)
        self.assertIn("`--output-json PATH` implies JSON output", readme)
        self.assertIn("python -m agent_workbench scan . --output-json .agent-workbench/repo-map.json", readme)
        self.assertIn("python -m agent_workbench scan . --format json", readme)
        self.assertIn("agent-workbench check [ROOT]", readme)
        self.assertIn("agent-workbench scan [ROOT] [--format text|json]", readme)
        self.assertIn("agent-workbench demo [--output PATH] [--adapter claude|codex|cursor|opencode|all] [--check] [--strict]", readme)
        self.assertIn("[--proof [PATH]]", readme)
        self.assertIn("agent-workbench init [ROOT] --output .agent-workbench --project-name NAME [--adapter claude|codex|cursor|opencode|all] [--check] [--strict]", readme)
        self.assertIn("agent-workbench init [ROOT] --output .agent-workbench --project-name NAME [--adapter claude|codex|cursor|opencode|all] [--check] [--strict] [--print-kickoff] [--format text|json] [--output-json PATH] [--proof [PATH]]", readme)
        self.assertIn("$ agent-workbench demo", readme)
        self.assertIn("$ tree .agent-workbench", readme)
        self.assertIn("--adapter claude|codex|cursor|opencode|all", readme)
        self.assertIn(".agent-workbench/", readme)
        self.assertIn("AGENTS.md", readme)
        self.assertIn("agent-task-pack.md", readme)
        self.assertIn("## Kickoff Prompt", readme)
        self.assertIn("## Verification Commands", readme)
        self.assertIn("examples/python-cli/source", readme)
        self.assertIn("examples/python-cli/agent-workbench/AGENTS.md", readme)
        self.assertIn("examples/typescript-cli/source", readme)
        self.assertIn("examples/typescript-cli/agent-workbench/AGENTS.md", readme)
        self.assertIn("uv tool install git+https://github.com/Xiao-rx/agent-workbench.git", readme)
        self.assertIn("docs/release-v0.8.0.md", readme)
        self.assertIn("Latest published release", readme)
        self.assertIn("releases/tag/v0.7.0", readme)
        self.assertIn("docs/launch-kit.md", readme)
        self.assertIn("MIT licensed, so reuse rights are explicit before adoption", readme)
        self.assertIn("License: [`MIT`](LICENSE)", readme)
        self.assertIn("python -m github_trend_lab insight --decisions reports/daily-decisions.json", readme)
        self.assertIn("`trend-lab insight` is a local shortcut", readme)
        self.assertIn("provider-neutral", readme.lower())
        self.assertIn("用一条命令把任意代码仓库变成 AI coding agent 可以安全接手的工作区", readme)
        self.assertIn("默认输出不绑定任何模型或工具", readme)

    def test_chinese_readme_covers_first_run_path(self):
        readme = Path("README.zh-CN.md").read_text(encoding="utf-8")

        self.assertIn("[English](README.md)", readme)
        self.assertIn("这是 Agent Workbench 的完整中文 README", readme)
        self.assertIn("用一条命令把任意代码仓库变成 AI coding agent 可以安全接手的工作区", readme)
        self.assertIn("agent-workbench demo --adapter all --strict --print-kickoff", readme)
        self.assertIn("agent-workbench demo --proof", readme)
        self.assertIn("`demo --proof [PATH]` 会写出 strict all-adapter JSON proof", readme)
        self.assertIn("stdout 打印同一份可复制的 `Proof:` 摘要", readme)
        self.assertIn("`Proof command:` 复现命令", readme)
        self.assertIn("agent-workbench init . --output .agent-workbench --proof", readme)
        self.assertIn("`init --proof [PATH]` 也会写出可分享的 JSON init proof", readme)
        self.assertIn("普通文本输出也会打印 `Proof:` 行", readme)
        self.assertIn("包含 adapter 与现有 agent asset 数量", readme)
        self.assertIn("运行 readiness check 时还会带上 readiness 数量", readme)
        self.assertIn("可复制的 readiness gate 命令", readme)
        self.assertIn("JSON proof 会包含 `kind`、`schema_version`、写入文件列表", readme)
        self.assertIn("简要 artifact summary", readme)
        self.assertIn("带有 `AGENTS.md`、`agent-task-pack.md` 和 `next_action` 的 `handoff` 对象", readme)
        self.assertIn("可复制的 `proof_summary`", readme)
        self.assertIn("可复现的 `proof_command`", readme)
        self.assertIn("首个 verification command", readme)
        self.assertIn("check 运行后的 `readiness_summary` 和 `readiness_counts`", readme)
        self.assertIn("会保留 adapter 和 strict 门槛的 `readiness_command` 与结构化 `readiness_args`", readme)
        self.assertIn("Python verification command 只会在匹配路径存在时报告", readme)
        self.assertIn("现有 agent 资产探测", readme)
        self.assertIn("scan JSON 也会包含 `kind`、`schema_version` 和 `agent_assets`", readme)
        self.assertIn("demo 仓库内置一个安全的 `.github/copilot-instructions.md`", readme)
        self.assertIn("写入前已经存在的 `agent_assets`", readme)
        self.assertIn(".github/copilot-instructions.md", readme)
        self.assertIn("GEMINI.md", readme)
        self.assertIn("如果希望 warning 也让 demo/init proof 失败", readme)
        self.assertIn("它会自动运行 readiness check", readme)
        self.assertIn("`--print-kickoff` 会把生成的 kickoff prompt 直接打印到终端", readme)
        self.assertIn("`--adapter all` 会一次生成 Claude Code、Codex、Cursor 和 OpenCode 的轻量适配文件", readme)
        self.assertIn(".codex/AGENTS.md", readme)
        self.assertIn("opencode.json", readme)
        self.assertIn("agent-workbench init . --output .agent-workbench --project-name my-repo --check", readme)
        self.assertIn("相对 `--output` 会解析到目标仓库根目录内", readme)
        self.assertIn("生成的 Codex 和 Cursor handoff 会指回同一个解析后的 workbench 路径", readme)
        self.assertIn("agent-workbench check . --format json", readme)
        self.assertIn("agent-workbench check . --strict --format json", readme)
        self.assertIn("agent-workbench check . --adapter all --format json", readme)
        self.assertIn("agent-workbench check . --output-json .agent-workbench/readiness.json", readme)
        self.assertIn("如果存在 Claude Code、Codex、Cursor 或 OpenCode handoff 文件", readme)
        self.assertIn("在 CI 里可以加 `--strict`", readme)
        self.assertIn("JSON readiness 报告会包含 `kind`、`schema_version`、`counts` 和 `next_action`", readme)
        self.assertIn("`--output-json PATH` 都会自动切到 JSON 输出", readme)
        self.assertIn("agent-workbench scan . --format json", readme)
        self.assertIn("examples/typescript-cli/source", readme)
        self.assertIn("python -m github_trend_lab insight --decisions reports/daily-decisions.json", readme)
        self.assertIn("快速查看最新决策摘要", readme)
        self.assertIn("许可证：[`MIT`](LICENSE)，复用权利明确", readme)
        self.assertIn("趋势分析不是产品本体", readme)


if __name__ == "__main__":
    unittest.main()
